### ISSUE TITLE
[Admin] Configure GitHub Repo

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/csi-3370-software-project#1]
**What is the use case? Please describe.**
The GitHub repo needs to be configured with automation, security settings, and more to effectively manage a 50 person group project on a single repo.

**Tasks to Complete**

- [x] Add Issue Labels - @andrewdimmer 
- [x] Add Project Milestones - @andrewdimmer 
- [x] Add Project Sprint Boards for each Team - @andrewdimmer 
- [x] Restrict Merges to Squash and Merge - @andrewdimmer 
- [x] Add Issue Templates for each Team (both Bug and Sprint Task) - @andrewdimmer 
- [x] Add Team List Documentation for Reference - @andrewdimmer 
- [x] Add GitHub Documentation for Reference - @andrewdimmer 
- [x] Configure Code Owners for Packages - @andrewdimmer 
- [x] Configure Google Style Guide Check - @andrewdimmer 
- [x] Configure Build and Test Check - @andrewdimmer
- [x] Configure Branch Protection (require checks) - @andrewdimmer 
- [x] Configure Branch Protection (require reviews) - @andrewdimmer 
- [x] Invite everyone to the Repo - @andrewdimmer

**Comment by andrewdimmer** [comment]
Added Issue Labels, Project Milestones, Project Sprint Boards, and Restricted to Squash and Merge during manual repo setup.

**Comment by andrewdimmer** [comment]
Branch Protection Configuration Complete.

**Comment by andrewdimmer** [comment]
Everyone has been invited to the repo, we are good to go!
