### ISSUE TITLE
[Admin] Create Use Case 1 Integration Tests

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/csi-3370-software-project#157]
**What is the use case? Please describe.**
Create integration tests that verify the end to end system functionality of each of the following things that may occur in Use Case 1.

**Tasks to Complete**

- [x] Test when the requested RFID does not match - @andrewdimmer 
- [x] Test when the requested RFID matches but no data exists - @andrewdimmer (SKIP; can't happen)
- [x] Test when the requested RIFD matches but not enough data exists for the course and speed - @andrewdimmer 
- [x] Test when the requested RFID matches and enough data exists for the course and speed - @andrewdimmer
