### ISSUE TITLE
[Admin] Create Use Case 2 Integration Tests

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/csi-3370-software-project#159]
**What is the use case? Please describe.**
Create integration tests that verify the end to end system functionality of each of the following things that may occur in Use Case 2.

**Tasks to Complete**

- [x] Test when in normal mode primary signal changes but stays strong enough to remain in normal mode - @andrewdimmer 
- [x] Test when in normal mode primary signal changes and mode switches to degraded mode - @andrewdimmer 
- [x] Test when in degraded mode primary signal changes but stays in degraded mode - @andrewdimmer 
- [x] Test when in degraded mode secondary signal changes by stays in degraded mode - @andrewdimmer 
- [x] Test when in degraded mode primary signal changes and mode switches to standby mode - @andrewdimmer 
- [x] Test when in degraded mode secondary signal changes and mode switches to normal mode - @andrewdimmer 
- [x] Test when in standby mode primary signal changes but stays in standby mode - @andrewdimmer 
- [x] Test when in standby mode secondary signal changes by stays in standby mode - @andrewdimmer 
- [x] Test when in standby mode primary signal changes and mode switches to degraded mode - @andrewdimmer 
- [x] Test when in standby mode secondary signal changes and mode switches to degraded mode - @andrewdimmer
