### ISSUE TITLE
[Admin] Create Public Interfaces and Shared Data Types

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/csi-3370-software-project#24]
**What is the use case? Please describe.**
Create the public Java interface for each interface in the `edu.oakland.production.admin` package, and the public methods for every data type in the `edu.oakland.helper.admin` package. Note that this is part of sprint deliverable task 2.3.2.

**Setup**

To be done by @brendanfraser597 , @TessaPeruzzi , or @andrewdimmer before the rest of the team starts working on it:

1. Use the documentation at https://github.com/andrewdimmer/csi-3370-software-project/tree/admin-production-uml-class-diagrams/docs/uml-class-diagrams/admin to identify the classes and interfaces to create.
2. Edit this issue message to add a checkbox for each class or interface, and assign it to the correct team member.

**Steps**

To be done by each team member for each class or interface they are creating:

1. Checkout and/or pull the branch `admin-public-interfaces`
2. Make the code changes to create the class or interface described in https://github.com/andrewdimmer/csi-3370-software-project/tree/admin-production-uml-class-diagrams/docs/uml-class-diagrams/admin
3. Test your changes locally with `gradle build` if you have Gradle installed, or test it with `./gradlew build` or `gradlew.bat build` if you do not.
4. Commit your changes with the message `[Admin] Created <<<Class/Interface_Name_Here>>>`
5. Push your changes
6. If you are the first person to push, create a pull request draft with the name `[Admin] Create Public Interfaces and Shared Data Types` and the rest of the information like description, tags, etc. For reference, the settings on the right hand side should match this issue, with the exception that the assignees on the PR are just those who are pushing code.
7. If you are the last person to push, release the pull request for reviews, and add @andrewdimmer as a reviewer.

**Tasks to Complete**

- [x] Assign Tasks - @brendanfraser597 , @TessaPeruzzi , or @andrewdimmer
- [x] Create LocationDataType - @andrewdimmer 
- [x] Create Satellite - @andrewdimmer 
- [x] Create TrackData - @andrewdimmer 

**Additional context**
Note: if for some reason you need to change a public interface or shared data type, reach out to @andrewdimmer who can help you manage making that BREAKING CHANGE.
