### ISSUE TITLE
[Display_02] Document Internal Class Implementation

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/csi-3370-software-project#39]
**What is the use case? Please describe.**
Document the internal implementation of classes in the `edu.oakland.production.display02` or `edu.oakland.helper.display02` packages. Note that this is part of sprint deliverable tasks 1.4, 1.5, 2.1.4, 2.1.5, and 2.3.2.

**Sprint Task Setup**

To be done by @jcortes18 , @sydneyhill3901 , or @Volter43 before the rest of the team starts working on it:

1. Use the documentation at https://github.com/andrewdimmer/csi-3370-software-project/tree/display_02-production-uml-class-diagrams/docs/uml-class-diagrams/display02 to identify the classes and `README.md` files to update.
2. Edit this issue message to add a checkbox for each class, and assign it to the correct team member(s).

**Software Setup**

For this task, you'll be updating PlantUML diagrams. To preview them on your local machine, set up:

- [Visual Studio Code](https://code.visualstudio.com/)
- [PlantUML Visual Studio Code Extension](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml)
- [Graphviz](https://graphviz.org/)

After that, you can open a .puml document, right click on it, and "Preview Current Diagram".

If you don't want to set that up though, you don't have to. When you commit, GitHub has been configured to automatically update all the diagrams, and you can push to GitHub then view the diagrams from there and/or pull them back to your current machine.

**Steps**

To be done by each team member for each class/interface or package they are documenting:

1. Checkout and/or pull the branch `display_02-production-uml-class-diagrams`
2. Open the docs in the `/docs/uml-class-diagrams/display02` folder.
3. Navigate via the links in the `README.md` (on GitHub to view) or the file structure (on your local machine to edit) to the class you're updating (or the package if you are updating the package README.md files).
4. Edit the correct `README.md` document, and/or the document titled `NAME_OF_CLASS.puml`. Need help with the PlantUML Diagram itself? Check out https://plantuml.com/class-diagram.
5. Commit your changes with the message `[Display_02] Added Class/Interface_Name_Here UML Class Diagram`
6. Push your changes
7. If you are the first person to push, create a pull request draft with the name `[Display_02] Document Internal Class Implementation` and the rest of the information like description, tags, etc. For reference, the settings on the right hand side should match this issue, with the exception that the assignees on the PR are just those who are pushing code.
8. If you are the last person to push, release the pull request for reviews, and add @andrewdimmer as a reviewer.

**What to Add for each Class**

- The methods from the interface the class implements (if any); note these can be copy and pasted the interface diagram that was completed before
- Any private class variables (above the `__`); note there should be at least 1 as you need a reference to the next class in the chain
- A constructor that initializes all the private variables that don't have setters (below the `__` but above the `.. Use Case 1 ..`)
- Any private methods for Use Case 1 (below the public methods for Use Case 1)
 - Any private methods for Use Case 2 (below the public methods for Use Case 2)

Feel free to add as many or few private methods as you'd like to, this only changes your internal implementation and is entirely up to the team.

**Tasks to Complete**

- [x] Assign Tasks - @jcortes18 , @sydneyhill3901 , or @Volter43 
- [x] Create Purpose Statement for Subteam - @jcortes18
- [x] Create Purpose Statement for Production package - @githubUsername
- [x] Create Purpose Statement for Helper package - @githubUsername
- [x] Create Purpose Statement for Test package - @githubUsername
- [x] Create Purpose for and Document <<<Class/Interface_Name_Here>>> - @githubUsername
- [x] etc.

**Additional context**
Note: if for some reason you need to change a public interface or shared data type, reach out to @andrewdimmer who can help you manage making that BREAKING CHANGE.

Note: if you need additional helper classes (and you likely will), just ping @andrewdimmer to get the file structure set up.
