### ISSUE TITLE
[Display_01] Define Testing Plan for Display_01 Production Classes

### ISSUE THREAD

**Issue by andrewdimmer** [andrewdimmer/csi-3370-software-project#56]
**What is the use case? Please describe.**
For test driven development, it is important to determine a test plan before just jumping in and writing tests and code. For this sprint task, you'll be developing a testing plan for all of the classes in the `edu.oakland.production.display01` package. Note: This issue is similar to #51, but is tracked differently as helper and production classes have different deliverable dates.

**Prerequisites**

Please makes sure that #38 is closed and merged to `main` before starting this, to ensure that all of the documentation you need for this is in the correct spot.

**Sprint Task Setup**

To be done by @EC01EC , @stevecatherman , or @casher-ou before the rest of the team starts working on it:

1. Use the documentation at https://github.com/andrewdimmer/csi-3370-software-project/tree/main/docs/uml-class-diagrams/display01/production to identify the classes that require a test plan.
2. Edit this issue message to add a checkbox for each class, and assign it to the correct team member(s). Be sure to balance your team between this issue at #51 . Note that the teams assigned here should also be the same teams in charge of building the appropriate classes in #67 .

**Software Setup**

For this task, you'll be updating PlantUML diagrams. To preview them on your local machine, set up:

- [Visual Studio Code](https://code.visualstudio.com/)
- [PlantUML Visual Studio Code Extension](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml)
- [Graphviz](https://graphviz.org/)

After that, you can open a .puml document, right click on it, and "Preview Current Diagram".

If you don't want to set that up though, you don't have to. When you commit, GitHub has been configured to automatically update all the diagrams, and you can push to GitHub then view the diagrams from there and/or pull them back to your current machine.

**Steps**

To be done by each team member for each class they are developing a test plan for:

1. Each team member should watch the first ~9 minutes of @andrewdimmer 's [Test Driven Development Crash Course](https://youtu.be/eSc0aY4GhPs)
2. One person should create a branch off of main called `define-Name_Of_Test_Class` (ex. the `Demo` test plan gets defined on a branch called `define-DemoTests`). Everyone else in the programming pair or group should then checkout that branch.
3. Open the Test Class UML Diagram at `/docs/uml-class-diagrams/display01/test/Name_Of_Test_Class/Name_Of_Test_Class.puml`.
4. Using the information in the video, record your tests on the Test Class UML Diagram you opened in step 3. Need help with the PlantUML Diagram itself? Check out https://plantuml.com/class-diagram. Feel free to use the existing class diagrams already provided at https://github.com/andrewdimmer/csi-3370-software-project/tree/main/docs/uml-class-diagrams/display01/production to help guide you in creating the test classes!
5. Commit your changes with the message `[Display_01] Define Name_Of_Test_Class`
6. Push your changes
7. Create a pull request with the name `[Display_01] Define Name_Of_Test_Class` and the rest of the information like description, tags, etc. For reference, the settings on the right hand side should match this issue, with the exception that the assignees on the PR are just those who are pushing code.
8. Once your test plan is complete, add @andrewdimmer as a reviewer.

**Tasks to Complete**

- [x] Allocate Team Members to Classes - @EC01EC , @stevecatherman , or @casher-ou 
- [x] Define DisplayGpsInterfaceImplementationTests - @reedsikorskiOU or @DLidz 
- [x] Define DisplayGpsManagerImplementationTests - @atpoynter or @elilley15 
- [x] Define DisplayGpsReceiverImplementationTests - @EC01EC or @casher-ou

**Additional context**
Note: if for some reason you need to change a public interface or shared data type, reach out to @andrewdimmer who can help you manage making that BREAKING CHANGE.

Note: if you run into merge conflicts, let @andrewdimmer know and he can help you resolve them.
